repos:
  - repo: local
    hooks:
      - id: test
        name: test
        entry: ./bin/test.sh
        language: script
      - id: lint
        name: lint
        entry: ./bin/lint_fmt.sh
        language: script
